$('.active').click(function(){
    $('.menu').toggleClass('d-n');
});
$('.close').click(function(){
    $('.menu').toggleClass('d-n');
});
$('.coment-active').click(function(){
    $('.fon-blur').toggleClass('d-n');
});
$('.coment-close').click(function(){
    $('.fon-blur').toggleClass('d-n');
});
$('.active01').click(function(){
    $('.menu-contacts').toggleClass('d-n');
});
$('.close-menu-contacts').click(function(){
    $('.menu-contacts').toggleClass('d-n');
});